-- IP Assist Supabase 스키마
-- 프로젝트: vhmwowukuzqxnvrkzyjy

-- 1. pgvector 활성화
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. 지식베이스 청크 테이블
CREATE TABLE IF NOT EXISTS knowledge_chunks (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category    text NOT NULL,
  sub_cat     text,
  doc_name    text NOT NULL,
  chunk_index integer,
  content     text NOT NULL,
  metadata    jsonb DEFAULT '{}',
  embedding   vector(1536),
  created_at  timestamptz DEFAULT now()
);

-- 3. HNSW 인덱스
CREATE INDEX IF NOT EXISTS knowledge_chunks_embedding_idx ON knowledge_chunks
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- 4. 벡터 유사도 검색 함수
CREATE OR REPLACE FUNCTION match_chunks(
  query_embedding vector(1536),
  match_count     integer DEFAULT 5,
  category_filter text    DEFAULT NULL
)
RETURNS TABLE (
  id          bigint,
  content     text,
  metadata    jsonb,
  doc_name    text,
  category    text,
  similarity  float
)
LANGUAGE plpgsql AS $$
BEGIN
  RETURN QUERY
  SELECT
    kc.id, kc.content, kc.metadata,
    kc.doc_name, kc.category,
    1 - (kc.embedding <=> query_embedding) AS similarity
  FROM knowledge_chunks kc
  WHERE
    (category_filter IS NULL OR kc.category = category_filter)
    AND kc.embedding IS NOT NULL
  ORDER BY kc.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- 5. 대화 이력 테이블
CREATE TABLE IF NOT EXISTS conversations (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id   text NOT NULL,
  user_name    text,
  department   text,
  category     text,
  messages     jsonb DEFAULT '[]',
  rfp_data     jsonb DEFAULT '{}',
  rag_score    float,
  status       text DEFAULT 'active',
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now()
);

-- 6. 헌법 조항 테이블
CREATE TABLE IF NOT EXISTS constitution_rules (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_type  text NOT NULL,
  content    text NOT NULL,
  is_active  boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

INSERT INTO constitution_rules (rule_type, content) VALUES
  ('거부조건',  '공급업체 이름을 임의로 추천하거나 특정 업체를 이유 없이 선호해서는 안 된다.'),
  ('행동제어',  'RFP 작성 시 근거 문서에 없는 조항을 임의로 추가해서는 안 된다.'),
  ('수치기준',  '계약금액 기준은 반드시 분류체계 문서의 수치를 인용해야 한다.'),
  ('행동제어',  '사용자가 법적 판단을 요구할 경우 반드시 전문가 상담을 권고해야 한다.'),
  ('거부조건',  '개인정보가 포함된 데이터를 학습 또는 기억해서는 안 된다.'),
  ('행동제어',  '답변에 RAG 근거 문서 출처를 반드시 명시해야 한다.');

-- 7. 공급업체 테이블
CREATE TABLE IF NOT EXISTS suppliers (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  category     text NOT NULL,
  score        integer DEFAULT 0,
  match_rate   integer DEFAULT 0,
  tags         text[] DEFAULT '{}',
  status       text DEFAULT 'active',
  created_at   timestamptz DEFAULT now()
);

-- 8. 분류체계 테이블
CREATE TABLE IF NOT EXISTS taxonomy (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  major       text NOT NULL,
  middle      text,
  minor       text,
  stage       text,
  stage_desc  text,
  created_at  timestamptz DEFAULT now()
);

-- 9. 관리자 사용자 테이블
CREATE TABLE IF NOT EXISTS admin_users (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  email       text UNIQUE NOT NULL,
  role        text NOT NULL DEFAULT 'viewer',
  department  text,
  is_active   boolean DEFAULT true,
  last_login  timestamptz,
  created_at  timestamptz DEFAULT now()
);

INSERT INTO admin_users (name, email, role, department) VALUES
  ('관리자', 'admin@castingn.com', 'superadmin', 'IT팀');

-- 10. 인덱스
CREATE INDEX IF NOT EXISTS knowledge_chunks_category_idx ON knowledge_chunks (category);
CREATE INDEX IF NOT EXISTS knowledge_chunks_doc_name_idx ON knowledge_chunks (doc_name);
