-- knowledge_faq 테이블 생성 (분류체계 포함)
-- Supabase Dashboard > SQL Editor에서 실행하세요.

CREATE TABLE IF NOT EXISTS knowledge_faq (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chunk_id        bigint REFERENCES knowledge_chunks(id),
  category        text NOT NULL,          -- 원본 chunk 카테고리 (PDF 파일명 기반)
  taxonomy_major  text,                   -- 대분류 (차량관리, 교육 서비스 등)
  taxonomy_middle text,                   -- 중분류 (법인차, 법정 의무 교육 등)
  doc_name        text NOT NULL,
  question        text NOT NULL,
  answer          text NOT NULL,
  embedding       vector(1536),
  metadata        jsonb DEFAULT '{}',
  created_at      timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS knowledge_faq_taxonomy_major_idx ON knowledge_faq (taxonomy_major);
CREATE INDEX IF NOT EXISTS knowledge_faq_category_idx ON knowledge_faq (category);

CREATE INDEX IF NOT EXISTS knowledge_faq_embedding_idx ON knowledge_faq
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- FAQ 유사도 검색 함수 (분류체계 필터 지원)
CREATE OR REPLACE FUNCTION match_faq(
  query_embedding        vector(1536),
  match_count            integer DEFAULT 5,
  category_filter        text    DEFAULT NULL,
  taxonomy_major_filter  text    DEFAULT NULL
)
RETURNS TABLE (
  id bigint,
  question text,
  answer text,
  doc_name text,
  category text,
  taxonomy_major text,
  taxonomy_middle text,
  chunk_id bigint,
  similarity float
)
LANGUAGE plpgsql AS $$
BEGIN
  RETURN QUERY
  SELECT
    f.id, f.question, f.answer,
    f.doc_name, f.category,
    f.taxonomy_major, f.taxonomy_middle,
    f.chunk_id,
    1 - (f.embedding <=> query_embedding) AS similarity
  FROM knowledge_faq f
  WHERE
    (category_filter IS NULL OR f.category = category_filter)
    AND (taxonomy_major_filter IS NULL OR f.taxonomy_major = taxonomy_major_filter)
    AND f.embedding IS NOT NULL
  ORDER BY f.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;
